# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_time',
            field=models.TimeField(),
        ),
    ]
